<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Productos.aspx.cs" Inherits="TP1.Productos" %>

<%@ Register assembly="System.Web.DataVisualization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" namespace="System.Web.UI.DataVisualization.Charting" tagprefix="asp" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        #form1 {
            margin-top: 0px;
        }
    </style>
</head>
<body id="PageBody" runat="server" style="margin: 0px; height: 277px; ">
    <form id="form1" runat="server" style="font-family: 'Segoe UI Light'; color: #FFFFFF; font-style: normal; font-weight: 400">
        <asp:Panel ID="Panel4" runat="server" BackColor="#003D33" Height="60px" Font-Size="Smaller" ForeColor="White" Font-Names="Segoe UI Light">
            <br />
            &nbsp;&nbsp;&nbsp;&nbsp;
            <asp:ImageButton ID="btn_Logout" runat="server" Height="30px" ImageAlign="Top" ImageUrl="~/Imagenes/round_logout_white_24dp.png" OnClick="btn_LogOut_Click" />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Label ID="Label1" runat="server" Font-Names="Segoe UI Light" Font-Size="Large" Text="Segunda Tarea Programada"></asp:Label>
            <br />
        </asp:Panel>
        <asp:Panel ID="Panel5" runat="server" BackColor="#00695C" Font-Size="XX-Large" Height="65px" DefaultButton="btn_filtrarNombre">
            <asp:TextBox ID="txt_Filtro" runat="server" placeholder="Filtrar" Font-Names="Segoe UI Light" Font-Size="Large" ForeColor="#003D33" Height="35px" style="margin-left: 10px; margin-top: 13px; margin-bottom: 0px" Width="300px"></asp:TextBox>
            &nbsp;<asp:ImageButton ID="btn_filtrarNombre" runat="server" BackColor="#439688" Height="45px" ImageAlign="Top" ImageUrl="~/Imagenes/round_search_white_24dp.png" style="margin-top: 10px" OnClick="btn_filtrarNombre_Click" />
            <asp:ImageButton ID="btn_Insertar" runat="server" BackColor="#439688" Height="45px" ImageAlign="Top" ImageUrl="~/Imagenes/round_add_white_24dp.png" style="margin-top: 10px" OnClick="btn_Insertar_Click" />
            <asp:Button ID="btn_Puestos" runat="server" BackColor="#439688" BorderStyle="None" Font-Names="Segoe UI Light" Font-Size="Large" ForeColor="White" Height="45px" OnClick="btn_Puestos_Click" Text="Listar Puestos" Width="120px" />
        </asp:Panel>
        
        <asp:GridView ID="dtg_Articulos" runat="server" GridLines="Vertical" HorizontalAlign="Center" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <HeaderStyle BackColor="#00695C" BorderColor="White" BorderStyle="Solid" BorderWidth="1px" ForeColor="White" />
            <RowStyle BorderColor="White" BorderWidth="1px" />
        </asp:GridView>
        <asp:SqlDataSource ID="TP2" runat="server" ConnectionString="<%$ ConnectionStrings:TareaProgramada2ConnectionString %>" SelectCommand="SELECT [Nombre], [ValorDocumentoIdentificacion], [IdDepartamento], [Puesto], [FechaNacimiento], [IdTipoIdentificacion] FROM [Empleado] WHERE ([Activo] = @Activo2) ORDER BY [Nombre]">
            <SelectParameters>
                <asp:Parameter DefaultValue="TRUE" Name="Activo2" Type="Boolean" />
            </SelectParameters>
        </asp:SqlDataSource>
        <asp:SqlDataSource ID="Alfabetico" runat="server" ConnectionString="<%$ ConnectionStrings:TareaProgramada1ConnectionString %>" SelectCommand="SP_Alfabetico" SelectCommandType="StoredProcedure"></asp:SqlDataSource>
        <br />
        <br />
&nbsp;&nbsp;&nbsp;&nbsp; Isaac Brenes Torres</form>
</body>
</html>
